### ISSUE TITLE
Updates to the WIki-page?

### ISSUE THREAD

**Issue by torkjellsdatter** [alidock/alidock#158]
After installing AliPhysics with alidocker (macOS Catalina), I have some suggestions for the Wiki-page: 

1) The screenshots from the Docker-app under "macOS post-installation" are outdated - or at least my Docker-app doesn't look anything like this. They should perhaps be updated?

2) Under "Build software from within alidock", there should perhaps be a sentence that tells the user to start under "Prepare your source code" in the [ALICE Analysis Tutorial](https://alice-doc.github.io/alice-analysis-tutorial/building/build.html). The first time around I went straight to building AliPhysics with `alidock exec aliBuild build AliPhysics --defaults next-root6 --debug` as the Wiki suggests, because I wasn't aware that I had to initialize the branch to master with `alidock exec aliBuild init AliPhysics@master` before building. 

3) I would also suggest adding a paragraph on how to access your local directories from within the alidock-environment, in case you want to run analyses on data placed locally. Following suggestions by Antoine Lardeux I added the following to my local `.bash-profile`: 

```
# execute alidock within the appropriate Python virtual environment / make alidock available command in bash
function alidock() {( source "/Users/idastorehaug/.virtualenvs/alidock/bin/activate" && command alidock "$@"; exit $?; )}

alidock -q status
retval=$?

if [ $retval -ne 0 ]; then
	echo "mounting local repo to alidock:"
	alidock --mount /Users/username:username:rw /usr:usr:rw << EOF
	exit
EOF
fi

# command to mount the local repo manually
alias alimount='alidock --mount /Users/username:username:rw /usr:usr:rw'
```
 (exchange _username_ with local username). The local directories are then available from _within_ the enviroment at `[alidock] ~ $> ../../mnt/username`

Otherwise, thank you for a neat setup!

**Comment by mconcas** [comment]
Hi, thanks for your feedback and suggestions! Sorry for the late reply.
In order:
1.  You are definitely right, as soon as I find some time I will update them. In case you are willing to contribute feel free to do that with a PR! :)
2.  For any upgrade to the analysis-tutorial documentation, which is very welcome, you can refer to the official repo. It is community maintained and improved. You can directly propose your ideas with a PR
3.  The feature for local mounts is not advertised (as a bunch of other features) as the tool is originally conceived for analysis tutorials, which do not require this feature. In order not to distract newcomers the feature is omitted.

As a side note on this: you don't need to define aliases to the alidock command, as you could instead save your preferences into a configuration file called `.alidock-config.yaml` in your home directory.
Configuration parameters are: (from `alidock --help`)
```yaml
---
dockName: alidock                # same as option --name
updatePeriod: 43200              # same as option --update-period
dontUpdateAlidock: false         # same as option --no-update-alidock
debug: false                     # same as option --debug
imageName: alisw/alidock:latest  # same as option --image
dirOutside: ~/alidock            # same as option --shared
mount: []                        # same as option --mount
dontUpdateImage: false           # same as option --no-update-image
useNvidiaRuntime: false          # same as option --nvidia
enableRocmDevices: false         # same as option --rocm
cvmfs: false                     # same as option --cvmfs
web: false                       # same as option --web
```
